version: 3

env:
  BASE_REGISTRY: ghcr.io/open-component-model

vars:
  NESTED_MODULES: api
  API_DIRS: '{{.ROOT_DIR}}/api/v1alpha1/...'
  MANIFEST_OUT: '{{.ROOT_DIR}}/api/crds/manifests'
  CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/api/v1alpha1/...'
  COMPONENTS: 'service-provider-ocm'
  REPO_URL: 'https://github.com/open-component-model/service-provider-ocm'

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true

tasks:
  build:img:build-test:
    desc: "Build image for current platform and tag without suffix for testing"
    cmds:
      - task: build:img:build
      - docker tag ${BASE_REGISTRY}/images/{{.COMPONENTS}}:{{.VERSION}}-linux-{{.ARCH}} ${BASE_REGISTRY}/images/{{.COMPONENTS}}:{{.VERSION}}
    vars:
      VERSION:
        sh: hack/common/get-version.sh
      ARCH:
        sh: uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/'

  test-e2e:
    desc: "Build image and run e2e tests"
    cmds:
      - task: build:img:build-test
      - VERSION={{.VERSION}} go test -v ./test/e2e/... -count=1
    vars:
      VERSION:
        sh: hack/common/get-version.sh