name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@f0c2058996a840e18e05a4ec731e4525e7a01063 # main
    secrets: inherit
