name: Validate Pull Request Content

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  validate_pr_content:
    uses: openmcp-project/build/.github/workflows/validate-pr-content.lib.yaml@f0c2058996a840e18e05a4ec731e4525e7a01063 # main
    secrets: inherit